### PR TITLE
Tax Improvements

### LINKED ISSUE #428: Different tax rates per product or destination
It's sometimes necessary to have products with different tax rates in the same store, for example one site I look after has products at the standard 20% VAT rate, but also a handful of zero VAT rated products. Additionally, it's often necessary to charge different taxes depending on the destination country, and I'm not sure the multi-site features are always going to be the most appropriate solution to that, as you might not want to set up entirely separate sites for each destination you ship to.

## What would you like to see added?

I think the simplest solution to this is to make taxes work in a similar way to shipping. Have a default built-in tax calculator class that functions in the same way as the current fixed tax approach, but allow developers to swap it out for custom classes. Just as an example each class could contain the following methods:

- `calculateTax(Order $order, Product $product)` - Returns the tax amount
- `checkApplicable(Address $address)` - Returns true/false

## Is there a workaround you can use in the meantime?

Not an elegant one. I guess you could set the tax rate to zero so SC doesn't calculate anything, and then just set all you prices to the tax inclusive values, but then you lose accurate tax information in your order data. And I dont think that would work for different taxes depending on destination.

## Would you be open to PR'ing the feature?

I dont think I have enough knowledge of SC internals to do that.

---

If this is something you'd like to see added, please leave a 👍 reaction to this issue.

### PR DESCRIPTION
**Pull request by duncanmcclean**
This pull request makes a number of improvements to the way tax is calculated in Simple Commerce.

**Concept of tax engines**

SC will have the concept of 'tax engines'. Essentially, these are implementations of a contract that calculate how much tax should be collected for a given line item.

A really basic and simple tax engine is provided below for reference:

```php
<?php

namespace DoubleThreeDigital\SimpleCommerce\Tax;

use DoubleThreeDigital\SimpleCommerce\Contracts\Order;
use DoubleThreeDigital\SimpleCommerce\Contracts\TaxEngine;
use DoubleThreeDigital\SimpleCommerce\Facades\Product;
use Illuminate\Support\Facades\Config;
use Statamic\Facades\Site;

class BasicTaxEngine implements TaxEngine
{
    protected $taxRate;
    protected $includedInPrices;

    public function __construct()
    {
        $taxConfiguration = collect(Config::get('simple-commerce.sites'))
            ->get(Site::current()->handle())['tax'];

        $this->taxRate = $taxConfiguration['rate'];
        $this->includedInPrices = $taxConfiguration['included_in_prices'];
    }

    public function name(): string
    {
        return __('Basic Tax Engine');
    }

    public function calculate(Order $order, array $lineItem): TaxCalculation
    {
        $product = Product::find($lineItem['product']);

        if ($product->isExemptFromTax()) {
            return new TaxCalculation;
        }

        $taxAmount = ($lineItem['total'] / 100) * ($this->taxRate / (100 + $this->taxRate));
        $itemTax = (int) round($taxAmount * 100);

        return new TaxCalculation($itemTax, $this->taxRate, $this->includedInPrices);
    }
}
```

Obviously, you can get as complicated as you want here but you'll need to bear in mind that this method will be called for each line item in an order, every time the totals are recalculated.

**Default tax engine**

Instead of shipping with a basic tax system like is available in v2.3 at the moment, where you set a single tax rate and you can either have a product at that tax rate or a product that's exempt, I'm bringing in a new system.

The new system is really, really similar to the way Craft Commerce handles its tax stuff. Essentially, you can create tax categories, those are the things attached to products.

You'll then also have tax zones which will define specific tax regions. Then you'll have tax rates, which combined with categories and zones will help to define the actual rates that should be applied to orders.

## To Do

* [x] Ensure buttons in CP for create/edit/delete are shown based on permission
* [x] Make the Tax Zone create/edit page faster (build an AJAX thing)
* [x] Actually write the tax thingy 😅 
* [x] Write some tests for the CP implementation
* [x] Consider if we actually need the `isExemptFromTax` method on products
* [x] Figure out icons for CP Nav
* [x] Automatically add `tax_category` field to product blueprint(s) if standard tax engine is enabled.
* [x] Add region option to addresses
* [x] Proper support for 'tax included in price' toggle in new standard tax engine
* [x] Create a default tax category for products where it's not defined (shouldn't be deletable unless default is changed)
* [x] Create a default tax rate for the default tax category
* [x] When a zone is deleted, delete the assosiated rates
* [x] When a category is deleted, delete the associated rates
* [x] Allow creating tax rate for 'Everywhere'
* [x] Only allow creating one tax zone for an area (eg: can't have two Scotland zones)
* [x] Actually implement region tax rate filtering
* [x] Show validation errors on CP page
* [x] Show when fields are required on the frontend
* [x] Ensure that create forms have `{{ old('whatever') }}` stuff on inputs
* [x] Easy way to configure tax engine specific config settings `tax_engine_config`?
* [x] Get our tests to work properly so we can test both engines at once 😂 
* [x] Custom validation rules for things (region exists, tax category exists etc)
* [x] **Question:** What happens if the customer's address doesn't have a tax zone assigned?
* [x] **Question:** Should the tax zone be determined by the customer's billing address or shipping address? (maybe this is something we should allow configuration over?)
* [x] **Question:** If no tax rate is available for a product in the cart, should we let the order checkout?

## Related issues

Fixes #428, #427

### CODE REVIEW

**Comment by francoismajor** [comment]
Hi @duncanmcclean 
Glad to see you're working on taxes. I'm trying to set up my site and couldn't figure out why the amounts weren't adding up.

The calculation for taxes when **included_in_prices** is **false** doesn't seem to be right. 

If I set the taxes to 10 (ie 10%) for a 20$ product, the amount is added to the price, but should be 2$, not 1.82$. It seems like the tax amount is always calculated as included, but then subtracted or added to the price.

Screen Shot 2021-07-28 at 1 19 10 PM

I can open a seperate issue if you want. Thought I'd give you a heads up for this PR though as the calculation doesn't seem to have changed.

`$taxAmount = ($itemTotal / 100) * ($taxConfiguration['rate'] / (100 + $taxConfiguration['rate']));`

Shouldn't it be something simple like this?
`$taxAmount = $itemTotal * ($taxConfiguration['rate'] / 100);`

I also noticed when changing the tax amount, the change is not reflected on the checkout/information page, no matter how many refresh/empty cache, etc. If I add a new item, it's updated. If I go to shipping it will also change. It seems like the information page doesn't update the cart totals... I tried changing the cart view to sc:cart:update redirect but this empties the cart when I try to go to another page. (This is less big of a deal as rates should not change often, but still, I feel the cart should always show accurate numbers).

Thanks!

UPDATE

Oops, posted to quick. I'm in Canada, taxes are based per province and generally we have two taxes (provincial and federal). Some provinces can combine both, but Quebec used to be added on the other tax. Anyways, I thought I'd mention this to consider in the upcoming taxes improvement. Zones could be countries but also provinces. Support for multiple taxes would be nice (we have 5% + 9.975%) but I can get away with 14.975%. Definitely need to support multiple taxes for a single website though, as taxes need to change as soon as we're selling cross provinces.

**Comment by duncanmcclean** [comment]
Hi @francoismajor,

I'm surprised anyone's properly taken a look into this, so thanks for that! It's very much still a work in progress 😆 

Which tax engine are you using? Have you defined one in your `config/simple-commerce.php` file? If not, it'll be using the 'legacy' one (the same one that's used in v2.3 right now). I've ported that across for testing purposes.

The new tax engine I'm building brings support for different rates per 'zone', so you'd essentially be able to create one rate for one region, one for another etc. And the rates are grouped together with categories.

I'll push up a fix shortly to change the way the tax is calculated with both of the engines. I've changed the way the tax is calculated so many times (after people saying it should work another way 😅 ), hopefully your code should fix the issue.

I'm not too sure what's going on around the totals being different on different pages. They should be the same everywhere. It should just get the values directly from the entry file. Could you create an issue for that so I can dig into it when I've got some time?

Thanks

**Comment by francoismajor** [comment]
Hey,
I'm on v2.3, sorry for the confusion 😅. I was just checking around for any existing issue or PR before opening one for the taxes.

I'll document the prices update issue seperately and I have opened a PR for the taxes calculation.

**Comment by duncanmcclean** [comment]
Ah gotcha - I'll change it in v2.3 👍

**Pull request merged**
