### PR TITLE
Check Metadata on adding Item

### PR DESCRIPTION
**Pull request by chellmann**
## Description

Metadata not considered when ensuring the product doesn't already exist in the cart

## Related Issues

no related issues

### CODE REVIEW

**Comment by duncanmcclean** [comment]
Sorry, I'm not sure I understand the issue here.

Could you provide a quick video showing the issue or some way to reproduce the issue?

**Comment by chellmann** [comment]
Yes of course!

Image a Product with an extra field - lets Say a customized Product with a Text for Engraving.
The Text would be saved in the Metadata array.
If we are not checking for the Metadata and adding the same Item (with different Text) to the Cart, the first added Metadata would be overwritten but the Quantity would be increased.

**Comment by duncanmcclean** [comment]
So you want the metadata to be taken into consideration as well as the product/variant in the cart? So you could have the same product in the cart twice but with two different bits of text?

**Comment by chellmann** [comment]
Yes exactly!

**Comment by duncanmcclean** [comment]
Right, okay!

I like the idea and understand why you'd want it but I think we're going to make this behaviour something people opt-in to using. Otherwise, we'd introduce a breaking change where the behaviour is different from what people are expecting & there would be no way for them to go back to the previous behaviour. 

Maybe we could provide an option to let user's specify which parts of the item they want to be unique, where they could do something like this:

```antlers
{{ sc:cart:addItem unique="product|metadata" }}
 <!-- All of the normal stuff in here... -->
{{ /sc:cart:addItem }}
```

Although, I'm not sure if that's the best way to approach it 🤔

**Comment by chellmann** [comment]
What about a Switch in the Config?

**Review by duncanmcclean — APPROVED** [review]
Thanks again for this PR! I've changed the key to `unique_metadata` and I added some tests to cover it.

Hope you have a great rest of your day!

**Pull request merged**
