### PR TITLE
Customer ID overwrite

### PR DESCRIPTION
**Pull request by JanJanssensDigiti**
Found a bug or maybe it was intentional?

When going through the checkout proces at the moment your personal info gets saved to the cart it checks if the email field is set. In this check it doesn't check if the email is already taken by a customer in your application. So it makes a new customer and overwrites the old one. 

This causes an issue with your order detail in the control panel. Because the customer id isn't linked anymore you first need to clear your cache to open that order without an Statamic exception. When you open that order the customer won't be linked anymore because the id won't exist.

I used basically the same code of the customer check (right above it) to fix this issue. It's probably better to put this in a findOrCreate() function within the CustomerRepository to prevent duplicate code. If you prefer it that way I can give it a shot but first I wanted to get your feedback on this before I'm changing to much code.

### CODE REVIEW

**Comment by duncanmcclean** [comment]
Hmm, I'm not sure I understand what this is fixing, maybe it's just because it's late haha. 

Would you mind providing some reproduction steps?

**Comment by JanJanssensDigiti** [comment]
I will do this tomorrow morning! Not sure if i'm currently capable of giving a clear description right now 😅. Should also probably go get some sleep. I have another really small fix for an seperate issue about the maximum_uses of coupons but I will also post that tomorrow in a seperate PR. 😉

**Comment by JanJanssensDigiti** [comment]
**How to reproduce**
I used the simple commerce starter kit as a reference. 

1. Place an order like you normally would
2. When it enters the CP make sure to check the created customer and its ID
3. Place another order with the same email as the customer that has been created in the previous order you made
4. If you check your new order now you will see everything is normal but if you check your previous one it throws an error.
5. You can clear this by just using `php please cache:clear`
6. When you get within the order detail of the old order you will see that the customer (in sidebar) isn't linked anymore because the ID isn't matching.

The customer is overwritten every time you place a new order. The new one will be fine but all the old ones will have this problem.

**Comment by duncanmcclean** [comment]
Thanks for the reproduction steps!

**Comment by duncanmcclean** [comment]
This should now be fixed in the [latest release](https://github.com/doublethreedigital/simple-commerce/releases/tag/v2.1.29).

**Comment by JanJanssensDigiti** [comment]
Thanks Duncan! Just a question out of interest in CartController.php your checking if customer isset right above this change happened. Where does this get used exactlly? Is it for a sort user login?

**Comment by duncanmcclean** [comment]
> Thanks Duncan! Just a question out of interest in CartController.php your checking if customer isset right above this change happened. Where does this get used exactlly? Is it for a sort user login?

Ah, yeah, so that's another way of setting a customer. So you can either do this if you just want to fill in the name and email:

```
{{ sc:cart:update }}
  <input name="name">
  <input name="email">
{{ /sc:cart:update }}
```

Or you can do it this way:

```
{{ sc:cart:update }}
  <input name="customer[name]">
  <input name="customer[email]">
{{ /sc:cart:update }}
```

The benefit with the second way is that you can also set other fields on the customer entry too.

```
{{ sc:cart:update }}
  <input name="customer[name]">
  <input name="customer[email]">
  <input name="customer[vip]" type="checkbox">
{{ /sc:cart:update }}
```

**Comment by JanJanssensDigiti** [comment]
Ow yes! That's pretty handy. Thanks for the info!

**Pull request merged**
