### PR TITLE
Add mark-as-shipped action and send customer notification

### PR DESCRIPTION
**Pull request by steffenschmidt**
This PR adds an action 'Mark as shipped' for single order entries when paid but unshipped. When running this action the order is being marked as shipped with a boolean flag and the given date. In addition it will send a notification to the customer that the order was shipped.

## To Do

* [X] Add action _Mark as shipped_
* [X] Send customer notification
* [X] Extend language file
* [X] Extend configuration file to make notification configurable
* [ ] Provide update script
* [x] Added a test
* [X] Updated the documentation

For the two open to dos I need help to complete both.

Let me know if there is anything you would like to do in other ways.

### CODE REVIEW

**Comment by duncanmcclean** [comment]
Thanks for this! I'll take a look when I have some time.

**Review by duncanmcclean — APPROVED** [review]
Looks good! I made a couple changes - added some documentation, adjusted some copy & wrote a test. 

Thanks for this!

**Comment by steffenschmidt** [comment]
Thanks for bringing this to the finish line!

**Comment by duncanmcclean** [comment]
No worries! Have a great weekend!

**Pull request merged**
