### PR TITLE
Change the way Simple Commerce handles the front-end

### LINKED ISSUE #197: A way to change the layouts
## Description
It might be useful for developers to use their own layouts etc instead of the ones provided by Simple Commerce itself.

Right now the solution for this is to customise the published routes inside the site's `resources/views/vendor` directory. This isn't the ideal situation, especially as people would want it to be 'more statamicy' (not sure if that makes sense)

I'd appreciate some feedback on how to actually achieve this, especially if people want to use their own view names.

The only solution that I can come up with is to have some configuration option but I don't really want to add more stuff into the configuration file but if that's what has to happen, that's what has to happen I guess.

### PR DESCRIPTION
**Pull request by duncanmcclean**
Before now, Simple Commerce has provided its own routing, controllers and views. However, this pull request drops all of that, instead cart and controller stuff will happen via forms to Statamic actions.

Here's a quick example of a checkout form that uses the `commerce:form` tag.

**In your template:**

```html
{{ commerce:form for='checkout' redirect='/thanks' class='flex flex-col w-full' }}
    <input type="text" name="name">
    <input type="text" name="email">

    <button>Checkout</button>
{{ /commerce:form }}
```

**And the output in your browser:**

```html
<form action="http://yourstore.test/!/simple-commerce/checkout" method="POST" class="flex flex-col w-full">
    <input type="text" name="name">
    <input type="text" name="email">
    
    <button>Checkout</button>

    <input type="hidden" name="_token" value="someRand0mSt6ff">
    <input type="hidden" name="redirect" value="/thanks">
</form>
```

To walk you through how it works. The `for` param chooses which action and method to use. You can also add a `redirect` attribute which will redirect your user to wherever you want when the form is successful. Any other parameters you add will just be added to the `<form>` element.

We'll also add in a CSRF field for you too, for good luck!

## Boilerplate
I've removed the boilerplate from this repo but it is still available and will be updated [over here](https://github.com/doublethreedigital/simple-commerce-example).

Eventually, I'll get round to putting this stuff in a starter kit to make it easier for people to whip up a store and get started!

## Breaking changes
This pull request brings **a lot** of breaking changes. Just gonna make a list here:
* Removes `routes` from the config (just remove those)
* Removes the boilerplate stuff, so you'll have to start from scratch building your own (or copy in the files from the example repo)
* Removed all of the web routes
* Any Simple Commerce actions can be accessed using the `{{ commerce:form }}` tag
* Removed the `url` attribute from any models, so stuff like `{{ product:url }}` will no longer work
* Removed the `{{ commerce:route }}` tag

## Related Issues
#197 

## To Do
* [x] Fix Antlers parsing issues ([https://github.com/statamic/cms/issues/1573](https://github.com/statamic/cms/issues/1573))

### CODE REVIEW

**Comment by zedix** [comment]
Hi Duncan. 

After thoughts: could be great if *all controllers*  could be overrided.

Maybe, you could write some`trait` and _publishes_ the controllers like Laravel do with the Auth controllers (LoginController, RegisterController...)

In example, you may want to publish:
```
<?php

namespace App\Http\Controllers;

use DoubleThreeDigital\SimpleCommerce\Helpers\UsesCartActions;
use Illuminate\Http\Request;

class CartController extends Controller
{
    use UsesCartActions;
}
```

**Comment by duncanmcclean** [comment]
> Maybe, you could write some`trait` and _publishes_ the controllers like Laravel do with the Auth controllers (LoginController, RegisterController...)

What sort of things do you think you would need to override? I don't thinking publishing the controllers is the best option.

**Comment by zedix** [comment]
In example, `CartController@store`, maybe I want to redirect elsewhere when adding an item:

```
return redirect('/elsewhere');
//return back()->with('success', 'Success! Product added to your cart.');
```

In CheckoutController, maybe I want to take control If I handle others fields etc.

**Comment by duncanmcclean** [comment]
> In example, `CartController@store`, maybe I want to redirect elsewhere when adding an item:
> 
> ```
> return redirect('/elsewhere');
> //return back()->with('success', 'Success! Product added to your cart.');
> ```
> 
> In CheckoutController, maybe I want to take control If I handle others fields etc.

This pull request allows for that, you just add `redirect` to the form parameters. Like so:

```
{{ commerce:form for='checkout' redirect='/thanks' class='flex flex-col w-full' }}
    <input type="text" name="name">
    <input type="text" name="email">

    <button>Checkout</button>
{{ /commerce:form }}
```

You can do that for any of the Simple Commerce actions.

**Pull request merged**
